param(
    [string]$ProjectRoot = ".",
    [switch]$RequireBuildOutput,
    [switch]$RequireInstallerOutput,
    [switch]$RequireInnoSetup
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Status {
    param(
        [ValidateSet("INFO", "OK", "WARN", "FAIL")]
        [string]$Level,
        [string]$Message
    )
    Write-Host "[$Level] $Message"
}

function Fail {
    param([string]$Message)
    Write-Status -Level "FAIL" -Message $Message
    exit 1
}

function Assert-Exists {
    param(
        [string]$Path,
        [string]$Label
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        Fail "$Label not found: $Path"
    }
    Write-Status -Level "OK" -Message "$Label found: $Path"
}

function Find-IsccPath {
    param([string]$Root)

    $candidates = @()
    if ($env:INNO_SETUP) {
        $candidates += (Join-Path $env:INNO_SETUP "ISCC.exe")
    }
    $candidates += "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
    $candidates += "C:\Program Files\Inno Setup 6\ISCC.exe"

    foreach ($p in $candidates) {
        if (Test-Path -LiteralPath $p) {
            return $p
        }
    }
    return $null
}

$root = (Resolve-Path -LiteralPath $ProjectRoot).Path
Write-Status -Level "INFO" -Message "Project root: $root"

$versionFile = Join-Path $root "VERSION.txt"
$buildApp = Join-Path $root "build_app.bat"
$buildInstaller = Join-Path $root "build_installer.bat"
$setupIss = Join-Path $root "setup.iss"
$distExe = Join-Path $root "dist\DocCompareAI\DocCompareAI.exe"

Assert-Exists -Path $versionFile -Label "VERSION.txt"
Assert-Exists -Path $buildApp -Label "build_app.bat"
Assert-Exists -Path $buildInstaller -Label "build_installer.bat"
Assert-Exists -Path $setupIss -Label "setup.iss"

$version = (Get-Content -LiteralPath $versionFile -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') {
    Write-Status -Level "WARN" -Message "VERSION format is not x.y.z: $version"
} else {
    Write-Status -Level "OK" -Message "VERSION format looks valid: $version"
}

$installerVersionIss = Join-Path $root "installer\version.iss"
if (Test-Path -LiteralPath $installerVersionIss) {
    $issText = Get-Content -LiteralPath $installerVersionIss -Raw
    if ($issText -match [regex]::Escape($version)) {
        Write-Status -Level "OK" -Message "installer/version.iss contains current version."
    } else {
        Write-Status -Level "WARN" -Message "installer/version.iss may not match VERSION.txt"
    }
} else {
    Write-Status -Level "WARN" -Message "installer/version.iss not found (can be generated by build scripts)."
}

if (Test-Path -LiteralPath $distExe) {
    Write-Status -Level "OK" -Message "Build output exists: $distExe"
} else {
    if ($RequireBuildOutput.IsPresent) {
        Fail "Required build output missing: $distExe"
    }
    Write-Status -Level "WARN" -Message "Build output missing: $distExe"
}

$isccPath = Find-IsccPath -Root $root
if ($null -eq $isccPath) {
    if ($RequireInnoSetup.IsPresent) {
        Fail "Inno Setup ISCC.exe not found."
    }
    Write-Status -Level "WARN" -Message "Inno Setup ISCC.exe not found."
} else {
    Write-Status -Level "OK" -Message "Inno Setup found: $isccPath"
}

$expectedInstaller = Join-Path $root ("installer\DocCompareAI_Setup_v{0}.exe" -f $version)
if (Test-Path -LiteralPath $expectedInstaller) {
    Write-Status -Level "OK" -Message "Installer output exists: $expectedInstaller"
} else {
    if ($RequireInstallerOutput.IsPresent) {
        Fail "Required installer output missing: $expectedInstaller"
    }
    Write-Status -Level "WARN" -Message "Installer output missing: $expectedInstaller"
}

Write-Status -Level "OK" -Message "Preflight completed."
exit 0
